cloud:
  aws:
    s3:
      bucket: rb-dev-s3-images
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

eureka:
  auth:
    serviceid: ${EUREKA_AUTH_SERVICEID:rebook-auth}
